databases:
  - name: book_app
    databaseName: book_app
    user: book_app

services:
  - type: web
    name: book_app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn book_app.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: book_app
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
