# Generated by Django 4.1.3 on 2022-11-15 05:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('read_on', models.DateTimeField(default=datetime.datetime(2022, 11, 15, 5, 25, 35, 620391, tzinfo=datetime.timezone.utc))),
                ('read_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('read_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
