# Generated by Django 4.1.3 on 2022-11-15 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 5, 56, 24, 111777, tzinfo=datetime.timezone.utc)),
        ),
    ]
