# Generated by Django 4.1.3 on 2022-11-15 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_read_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 19, 10, 19, 795748, tzinfo=datetime.timezone.utc)),
        ),
    ]
