# Generated by Django 4.1.3 on 2022-11-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
