# Generated by Django 4.1.3 on 2022-11-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_image_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default_book.jpg', upload_to='book_pics'),
        ),
    ]
