# Generated by Django 4.1.3 on 2022-11-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookread'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookread',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
